[package]
name = "queue"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
mmap-io = "0.9"
thiserror = "2.0"

[dev-dependencies]
tempfile = "3.0"
