name: Release PR

on:
  workflow_call:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-plz-pr:
    name: Create Release PR
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'crrow' && github.ref == 'refs/heads/main' }}
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: false
          persist-credentials: false
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9 # stable
        with:
          toolchain: stable
      - name: Install protoc
        uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3.0.0
        with:
          version: '25.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Clean ignored files
        run: |
          rm -rf bin/
          git clean -fdX
      - name: Run release-plz
        uses: release-plz/action@f708778669256143d984cce4b23592637532e040 # v0.5
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
