name: Web

permissions:
  contents: write

on:
  workflow_dispatch:
  pull_request:
    paths:
      - docs/**

  push:
    branches:
      - stable
      - main
    paths:
      - docs/**

jobs:
  web:
    name: Build and deploy site and docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561 # stable
      - uses: swatinem/rust-cache@ad397744b0d591a723ab90405b7247fac0e6b8db # v2

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@e7cc28468cf17df7cb288daea80c0c5437af360b # main
        env:
          BINSTALL_VERSION: v1.16.6

      - name: Install mdbook plugins
        run: |
          cargo binstall --locked --no-confirm mdbook
          cargo binstall --locked --no-confirm mdbook-toc@0.11.2
          cargo binstall --locked --no-confirm mdbook-mermaid@0.17.0
          cargo binstall --locked --no-confirm mdbook-linkcheck@0.7.7

      - name: Build mdbook
        run: |
          mdbook build docs

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        if: ${{ github.event_name == 'push' }}
        with:
          branch: gh-pages
          folder: docs/book
          token: ${{ secrets.GITHUB_TOKEN }}
          single-commit: true
