name: Web

permissions:
  contents: write

on:
  workflow_dispatch:
  pull_request:
    paths:
      - docs/**

  push:
    branches:
      - stable
      - main

concurrency:
  group: web-${{ github.ref }}
  cancel-in-progress: true

jobs:
  web:
    name: Build and deploy site and docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: false
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561 # stable
        with:
          toolchain: stable
      - uses: swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install mdbook plugins
        run: |
          cargo binstall mdbook-toc@0.11.2
          cargo binstall mdbook-mermaid@0.17.0
          cargo binstall mdbook-linkcheck@0.7.7

      - name: Build mdbook
        run: mdbook build docs

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        if: ${{ github.event_name == 'push' }}
        with:
          branch: gh-pages
          folder: docs/book
          token: ${{ secrets.GITHUB_TOKEN }}
          single-commit: true
